---
title: "Trends"
author: "Anna Tenias"
date: "28/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gtrendsR)
library(ggplot2)
beyonce.trend <- gtrends(c("beyonce"), gprop = "web", time = "all")[[1]]

ggplot(data = beyonce.trend) + geom_line(mapping = aes(x= date, y = hits))
```
```{r}
ggplot(data = beyonce.trend) + 
  geom_line(mapping = aes(x= date, y = hits)) +
  geom_vline(xintercept = as.Date("2003-06-24"), color = "red") +
  geom_vline(xintercept = as.Date("2006-09-04"), color = "red") +
  geom_vline(xintercept = as.Date("2008-11-14"), color = "red") +
  geom_vline(xintercept = as.Date("2011-06-24"), color = "red") +
  geom_vline(xintercept = as.Date("2013-12-13"), color = "red") +
  geom_vline(xintercept = as.Date("2016-04-23"), color = "red")
```

- 24 juin 2003 : Dangerously in love

- 4 septembre 2006 : B'Day

- 14 novembre 2008 : I ... am Sacha Fierce

- 24 juin 2011 : 4

- 13 décembre 2013 : Beyoncé

- 23 avril 2016 : Lemonade

## Conclusions
We can see that each time Beyonce releases an album, there is a pick in google researches